config/routes.rb
StdApp::Application.routes.draw do

  

  resources :students

root :to => "students#index"
get '/search' => 'students#search'
get '/search_data' => 'students#search_data'

end

app/models/student.rb
class Student < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def new
		@student=Student.new
	end

	def create
		@student=Student.new(user_params)
		if @student.save
		flash[:success]="Successfully saved" 
		redirect_to students_path
	    else
	    render "new"
	    end
	   
	end

	def edit
		@student=Student.find(params[:id])
	end

	def update
		@student=Student.find(params[:id])
		if  @student.update_attributes(user_params)
			flash[:success]="Successfully updated"
			redirect_to students_path
		else
			render edit
		end
	end

	def destroy
		@student=Student.find(params[:id])
		@student.destroy
		flash[:success]="Successfully deleted"
		redirect_to students_path
	end

	def index
		@student=Student.all
	end

	def search
		if !params[:commit].nil?
			@name=params[:name] if !params[:name].nil?
			@age=params[:age] if !params[:age].nil?
			@gender=params[:gender] if !params[:gender].nil?
			@standard=params[:standard] if !params[:standard].nil?
			var=[]
			var << ["std_name"=>@name] <<["age"=> @age] <<["gender"=> @gender] <<["standard"=>@standard]
			arr=var.flatten.inject(&:merge)
			str=''
			arr.each do |k,v|
				unless v.blank? 
					str= k + "=" + "'#{v}'" + " and " + str
				end
			end
			str=str.split(' ')[0...-1].join(' ')
			@student=Student.where(str)	
			# var = "std_name LIKE " + @name +" and " + " age in " + @age  +" and " + " gender LIKE " + @gender
			# @stu=Student.where()
			# # @stu=Student.find_by_sql [
			# # 	"select id from students where std_name in (?) 
			# # 	union 
			# # 	select id from students where age in (?)
			# #     union 
			# #     select id from students where standard in (?) 
			# #     union 
			# #     select id from students where gender in (?);","#{params[:name]}","#{params[:age]}","#{params[:standard]}","#{params[:gender]}"]
		 # #    @stu2=Student.find_all_by_id(@stu)
		 # #    # p @stu2
		 #    # p @stu2
		 #    # p @stu2
		 #    # p "%%%%%%%%%%%%%%%"
		 #    # @student=@stu2.find_by_std_name_and_age(params[:name],params[:age])
			# #@student=@stu2.find(var)
			# 	#std_name LIKE in (?) :gender LIKE in (?)","%#{@name}%","%#{@gender}%"
			# 	#@gender,:age=>@age,:standard=>@standard})
			# # p "%%%%%%%%%%%%%%%"
			# # p "%%%%%%%%%%%%%%%"
			# # p @student
   #          # p @name
   #          # p @age
   #          # p @gender
   #          # p @standard
			# # "select distinct s.id from 
			# # (select * from students where std_name like %#{params[:name]}%) as s,
			# # (select * from students where age=#{params[:age]}) as s1, 
			# # (select * from students where standard like %#{params[:standard]}%) as s2,
			# # (select * from students where gender like %#{params[:gender]}%) as s3 
			# # where s.id=s1.id or s2.id=s1.id or s2.id=s3.id or s3.id=s1.id;"
			# #@student=ActiveRecord::Base.connection.execute(@sql)
			# #Student.where('std_name LIKE :name OR age =:age' ,{:name=>"%#{params[:name]}%" ,:age=>"#{params[:age]}"}) #or 'age LIKE ?' or 'gender LIKE ?' or 'standard LIKE ?'
			  @back=search_path
			render 'search_data'
		end
			#,"%#{params[:age]}%","%#{params[:gender]}%","%#{params[:standard]}%"		
	end
	def search_data
      
	end
	private
	def user_params
    	params.require(:student).permit(:std_name,:age,:gender,:standard,:father_name,:mother_name,:address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/standard_helper.rb
module StandardHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StdApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/edit.html.erb
<h1>Edit student</h1>
<%=flash[:success]%>
		<%= form_for(@student) do |f| %>
		<%= f.label :student %>
		<%=f.text_field :std_name %><br />
		<%= f.label :age %>
		<%=f.text_field :age %><br />
		<%= f.label :gender %>
		<%=f.text_field :gender %><br />
		<%= f.label :standard %>
		<%=f.text_field :standard %><br />
		<%= f.label :father_name %>
		<%=f.text_field :father_name %><br />
		<%= f.label :mother_name %>
		<%=f.text_field :mother_name %><br />
		<%= f.label :address %>
		<%=f.text_field :address %><br />
		
		<%= f.submit  "Add student" %>
<% end %>

app/views/students/index.html.erb
<h1>Students</h1>
	<table border=1>
	<tr>
	<td>Name</td>
	<td>Age</td>
	<td>Gender</td>
	<td>Standard</td>
	<td>Father's Name</td>
	<td>Mother's Name</td>
	<td>Address</td>
	<td>Actions</td>
	</tr>
	<% @student.each do |c| %>
	<tr>
		<td><%=c.std_name%></td>
		<td><%=c.age%></td>
		<td><%=c.gender%></td>
		<td><%=c.standard%></td>
		<td><%=c.father_name%></td>
		<td><%=c.mother_name%></td>
		<td><%=c.address%></td>
		<td><%= link_to "new", new_student_path %>
		<%= link_to "Edit", edit_student_path(c) %>
		<%= link_to 'Destroy', c, :confirm => 'Are you sure?', :method => :delete %>
		</td>
	</tr>
	<%end%>
	</table>

app/views/students/new.html.erb
<h1>Add new student</h1>
<%=flash[:success]%>
		<%= form_for(@student) do |f| %>
		<%= f.label :student %>
		<%=f.text_field :std_name %><br />
		<%= f.label :age %>
		<%=f.text_field :age %><br />
		<%= f.label :gender %>
		<%=f.text_field :gender %><br />
		<%= f.label :standard %>
		<%=f.text_field :standard %><br />
		<%= f.label :father_name %>
		<%=f.text_field :father_name %><br />
		<%= f.label :mother_name %>
		<%=f.text_field :mother_name %><br />
		<%= f.label :address %>
		<%=f.text_field :address %><br />
		
		<%= f.submit  "Add student" %>
<% end %>

app/views/students/search.html.erb
<h1>Search<h1>

<%= form_tag("/search", method: "get") do %>
  <%= label_tag(:q, "Name:") %>
  <%= collection_select(@var,'name',Student.uniq.select('std_name'),:std_name,:std_name,{:include_blank => ''})%><br/>
  <%#= select_tag "Name", options_for_select(Student.collect{|std| std.std_name})%>
  <%= label_tag(:q, "Age:") %>
  <%= collection_select(@var,'age',Student.uniq.select('age').order(:age),:age,:age,{:include_blank => ''})%><br/>
  <%= label_tag(:q, "Standard:") %>
  <%= collection_select(@var,'standard',Student.uniq.select('standard').order(:standard),:standard,:standard,{:include_blank => ''})%><br/>
  <%= label_tag(:q, "Gender:") %>
  <%= collection_select(@var,'gender',Student.uniq.select('gender'),:gender,:gender,{:include_blank => ''})%><br/>
  <%= submit_tag("Search") %>
<%end%>

app/views/students/search_data.html.erb
<h1>Students</h1> <%= link_to "back", @back%>

<%if @student.blank?%>
<h1>No data found</h1>
<%else%>
	<table border=1>
	<tr>
	<td>Name</td>
	<td>Age</td>
	<td>Gender</td>
	<td>Standard</td>
	<td>Father's Name</td>
	<td>Mother's Name</td>
	<td>Address</td>
	<td>Actions</td>
	</tr>
	<% @student.each do |c| %>
	<tr>
		<td><%=c.std_name%></td>
		<td><%=c.age%></td>
		<td><%=c.gender%></td>
		<td><%=c.standard%></td>
		<td><%=c.father_name%></td>
		<td><%=c.mother_name%></td>
		<td><%=c.address%></td>
		<td><%= link_to "new", new_student_path %>
		<%= link_to "Edit", edit_student_path(c) %>
		<%= link_to 'Destroy', c, :confirm => 'Are you sure?', :method => :delete %>
		</td>
	</tr>
	<%end%>
	
	<br/>
	</table>
<%end%>